name: .NET format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dotnet-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.x.x

    - name: Install MAUI Android Workload
      run: dotnet workload install maui-android

    - name: Restore dependencies
      run: dotnet restore

    - name: Format
      run: dotnet format --verify-no-changes --verbosity diagnostic